DROP TABLE IF EXISTS CREDIT_CARDS_ACCOUNT;

CREATE TABLE CREDIT_CARD_ACCOUNT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(15) NOT NULL,
  card_number VARCHAR(20) UNIQUE NOT NULL,
  currency VARCHAR(5) NOT NULL,
  balance NUMERIC(15, 2) NOT NULL,
  credit_limit NUMERIC(15, 2) NOT NULL
);


